### ISSUE TITLE
Clipped raster has different resolution than source tif?

### ISSUE THREAD

**Issue by bkavlak** [Taknok/Qgisplugin-ClipMultipleLayers#19]
I'm clipping a raster that has 10x10m resolution, but when I clip the image, the output does not has an exact 10x10m resolution.

I am not sure how to reproduce the example but here are the SS of the input and the output:

*INPUT:*
![Screenshot from 2020-07-22 11-56-30](https://user-images.githubusercontent.com/36866123/88157038-e9127500-cc12-11ea-9ab8-96e7cb48ff20.png)

*OUTPUT:*
![Screenshot from 2020-07-22 11-56-39](https://user-images.githubusercontent.com/36866123/88157102-fdef0880-cc12-11ea-8530-35ebfcb9962d.png)

**Comment by Taknok** [comment]
I will suppose a rectangular raster in a flat plan to simplify my though. 

My guess is:
You have a orginal (ractanglular) `origin_raster` which has 20983 x 10981 (m x m) for dimension. 1 pixel code for a 10 x 10 (m x m) square. 
Pb n°1 : It is a bit strange because it leave 0.3 pixel on X-axis and 0.1 pixel on Y-axis.

Then you cut to 5407 x 3925 to `cut_raster`. "Unfortunately", the new witdh and length are not a multiple with the old dimensions :
```
W: 20983 ÷ 5407 = 3,88071019049
L: 10981 ÷ 3925 = 2,79770700636
```
Which leads to a pixel "cut" on the edges for `cut_raster`. So one width edge you have 0.88 pixel and on length edge 0.79 pixel instead of 1 complet. Those partials edges pixels change the means resolution a little.

Do you agree with my though ?

**Comment by bkavlak** [comment]
Thanks for the explanation! I missed ```Keep resolution of input raster``` parameter in ```Clip Raster By Mask Layer```. That way resolves the issue. This corresponds to:

```gdalwarp -tr 10.0 -10.0``` parameter in which the output resolution is defined. It may deal the issue considering your reasoning.
