### ISSUE TITLE
images became brighter

### ISSUE THREAD

**Issue by geszter** [Taknok/Qgisplugin-ClipMultipleLayers#4]
The output image is brighter, with more whites.
the output:
![capture_1](https://cloud.githubusercontent.com/assets/11259505/14850980/ee11d9ba-0c7c-11e6-9d1e-1b9c8d6f3f91.PNG)
the original:
![capture_2](https://cloud.githubusercontent.com/assets/11259505/14850982/efc60772-0c7c-11e6-8dbc-37134bdfd5ba.PNG)

**Comment by Taknok** [comment]
Ok, thank you. Could you send me your image ? To run several test and solve the pb.
Thk for the report.

**Comment by stefanon** [comment]
I experienced the same effect that is visible as a brighter image, but it's not  only brighter, data values change so I have a clipped raster with different values than the original.

**Comment by Taknok** [comment]
Which version of Qgis are you using ? And the plugin version ? Your raster is in `.tif` ? 
I do not have any raster that trigger this issue, it would be nice if you could send me at least one raster to investigate on this bug.

**Comment by stefanon** [comment]
QGIS version 2.18.11, plugin 0.1.5 
Raster was in ESRI Grid format .ADF, file in question is rather big, I'll try to cut a piece for test.

**Comment by Taknok** [comment]
The format is probably the issue. The plugin deals with gtiff format. I tried to obtain the same file as you, but I'm not familiar with ESRI Grid. When I converted my `.tif` to an Arc/Info Binary (`.adf`) with the Qgis translate tool the picture is brighter. When I converted my `.tif` to an ESRI ( Qgis specified `.bil`), the picture keep the color.
I will try to implement smooth conversion to handle other format than `.tif`. In the mean time, try to use gtiff format :/

**Comment by Taknok** [comment]
__Short__ : After some intensives researches, it appears that your file isn't supported by gdal in qgis for a weird reason, I will post an issue on QGIS repository to have more explanations.

__Full__ : Qgis implement an wrapper to use gdal. This wrapper have some automatics functions that can't be override. One function is in charge of detecting the file extension and set the output format accordingly. But this function ([`getFormatShortNameFromFilename`][1]) always return `Gtiff` for `ESRI` format. This is due to [`getSupportedRasters`][2] where the `if DMD_EXTENSION in metadata` return **false**. So the question is why this `DMD_EXTENSION` isn't in the wrapper meta, even if the conversion from command line (shell) work ?

Well of course I could re-implement all the wrapper, but ... I have other things to do ! I will let Qgis dev team works on this for everyone.

[1]: https://github.com/qgis/QGIS/blob/release-2_18/python/plugins/processing/algs/gdal/GdalUtils.py#LC167
[2]: https://github.com/qgis/QGIS/blob/release-2_18/python/plugins/processing/algs/gdal/GdalUtils.py#LC113

**Comment by stefanon** [comment]
thank you for the details. this problem involves all the non gtiff formats uses in QGIS other than this plugin? i.e. if I read an .adf in QGIS am I getting wrong raster values as I experienced after clipping?

**Comment by Taknok** [comment]
> this problem involves all the non gtiff formats uses in QGIS other than this plugin?

No, this is the strange part, Qgis handle a large amount of formats, including .adf. That mean if you open your raster in Qgis it will be loaded in the right way. The library GDAL, used by Qgis, is a processing library providing tools to compute raster. It handles also a large amount of formats including ESRI. So you can open a shell and use the shell command to compute your ESRI raster, the output will be ok, and if you drag and drop it in QGIS it will still be ok.
**But** if you tried to do it in once (from inside Qgis), this will not work. This because the link between both, created by Qgis, is bugging with some extensions.
___
As workaround I see 2 possibilities : 
1. You used GDAL in shell with your own script and then import the ouput. The command will be something like 
```bash
gdalwarp -q -cutline PATH2SELECTION.shp -tr RESOLUTIONX RESOLUTIONY -of EHdr PATH2INPUT.adf PATH2OUTPUT.adf
```
 You can install Gdal or used the one installed in 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Mac : `/Library/Frameworks/GDAL.framework/Versions/2.1/Programs/gdalwarp`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Windows : `C:\Program Files\QGIS 2.18\bin`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Linux : `/usr/bin`

2. Convert you raster to Gtiff format which is the default format in QGIS with *Raster > Conversion > Translate* (or use `gdal_translate` from shell which is the same but less userfriendly)
<br>
Ps : I have posted the bug in QGIS and I'm still waiting an answer from the dev team about this. To see how we can fix it instead of unpractical workaround.

**Comment by Taknok** [comment]
@stefanon Did you manage to get proper image ?

**Comment by stefanon** [comment]
@Taknok I did the needed clipping from QGIS menu raster - extraction - clipper that calls gdalwarp with the needed parameters and worked, thanks again for infos and for following the issue.

**Comment by Taknok** [comment]
Ok, I'm glad that you manage to get the result wanted. Just for information what is the command displayed in the box at the bottom of clipper with your raster ?
