### ISSUE TITLE
Error when running on 2.18.7

### ISSUE THREAD

**Issue by shtirlitsDva** [Taknok/Qgisplugin-ClipMultipleLayers#8]
Hi
I have previously used the plugin with great effect.

Today, on a fresh windows and qgis install, I am getting the following error:

`Traceback (most recent call last):
			  File "C:/Users/user/.qgis2/python/plugins\ClipMultipleLayers\Clip_Multiple_Layers.py", line 236, in run subprocess.call(command_cut)
File "C:\OSGEO4~1\apps\Python27\lib\subprocess.py", line 524, in call return Popen(*popenargs, **kwargs).wait()
File "C:\OSGEO4~1\apps\Python27\lib\subprocess.py", line 711, in __init__ errread, errwrite)
File "C:\OSGEO4~1\apps\Python27\lib\subprocess.py", line 948, in _execute_child startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd8' in position 69: ordinal not in range(128)`

**Comment by shtirlitsDva** [comment]
I have determined that the error was caused by a raster layer with the name "Navne basis kort". Haven't tried on other raster layers -- usually work with vector data.

**Comment by Taknok** [comment]
Hello

Yes, the error log say that the error is due to an encoding problem. This `'ascii' codec can't encode character u'\xd8' in position 69` signify that Qgis can't encode your string. Qgis works in ascii (an encoding method of char) and your string encodes char in utf-8 (another way) at the convertion, the ascii doesn't support the char u'\xd8' which seems to be an O with stroke (the O in Kort ?). Try to change this letter and Qgis gonna run.

**Comment by Taknok** [comment]
Is this problem resolved ?

**Comment by shtirlitsDva** [comment]
I am sorry, I haven't had time to look into it. Please close the issue --
if it resurfaces, I will reopen it.

18 мая 2017 г. 3:37 ПП пользователь "Pg" <notifications@github.com> написал:
